# cam_model: Pinhole
# cam_width: 1920
# cam_height: 1080
# scale: 0.5
# cam_fx: 1293.56944
# cam_fy: 1293.3155
# cam_cx: 626.91359
# cam_cy: 522.799224
# cam_d0: -0.076160
# cam_d1: 0.123001
# cam_d2: -0.00113
# cam_d3: 0.000251

cam_model: Pinhole
cam_width: 1920
cam_height: 1080
scale: 0.5
cam_fx: 857.8613980920594    # 取自focal_x（需确认单位）
cam_fy: 857.8613980920594    # 取自focal_y
cam_cx: 714.8384875297352    # 需重新计算或直接采用目标值
cam_cy: 590.2313556353744
cam_d0: -0.076160            # 对应k1（需验证符号）
cam_d1: 0.123001             # 对应k2
cam_d2: -0.00113             # 对应p1
cam_d3: 0.000251             # 对应p2